### ISSUE TITLE
No error with repulsive forces turned on and no residues specified

### ISSUE THREAD

**Issue by althea-hansel** [forlilab/cosolvkit#21]
Code executes if repulsive forces set to true but no residues are specified. This causes a `Particle is NaN` error during equilibration. Expect a warning to be raised

**Comment by nbruciaferri** [comment]
Are you sure that the `Particle is NaN` error is coming from the repulsive force? In theory that should not affect the equilibration since no custom force would be applied if no residues are specified.

Can you confirm that if you build the system with `add_repulsive=false`  the equilibration works?

**Comment by althea-hansel** [comment]
Manu and I debugged the `Particle is Nan` today, it is running perfectly with `add_repulsive=false`. I have no idea why it is like this

**Comment by nbruciaferri** [comment]
Okay cool! Thanks for finding the bug, I'll try to look at it asap.
